- name: "api"
  color: "0052CC"
  description: "Issue or PR related to API design or implementation"
  aliases:
    - "api"

- name: "blocked 🚧"
  color: "#e99695"
  description: "Issue or PR have some block to advance"
  aliases:
    - "blocked"

- name: "breaking change 💥"
  color: "925845"
  description: "Issue or PR adding a breaking change. Major version bump required"
  aliases:
    - "breaking change"

- name: "bug report 🐞"
  color: "FC2803"
  description: "Report a new bug"
  aliases:
    - "bug"

- name: "bugfix 🔧"
  color: "FC4E03"
  description: "Issue or PR related to something isn't working"
  aliases:
    - "bugfix"

- name: "ci 🏗️"
  color: "FF7A0E"
  description: "Issue or PR releated to Continuous Integration (CI) pipeline enhancements"
  aliases:
    - "ci"

- name: "codex ✨"
  color: "111112"
  description: "PR opened by Codex"
  aliases:
    - "codex"

- name: "compliance 📜"
  color: "AE6B09"
  description: "Issue or PR releated to enhancement to be compliant with something"
  aliases:
    - "compliance"

- name: "copilot ✨"
  color: "111112"
  description: "PR opened by Copilot"
  aliases:
    - "copilot"

- name: "cursor ✨"
  color: "111112"
  description: "PR opened by Cursor"
  aliases:
    - "cursor"

- name: "dependabot 🤖"
  color: "0052CC"
  description: "Dependabot alert"
  aliases:
    - "dependabot"

- name: "deprecate 🪦"
  color: "5F6A70"
  description: "Issue to deprecate some existing feature"
  aliases:
    - "deprecate"

- name: "documentation 📃"
  color: "0075CA"
  description: "Issue or PR releated to improvements or additions to documentation"
  aliases:
    - "docs"

- name: "duplicate !!"
  color: "CFD3D7"
  description: "This issue or pull request already exists"
  aliases:
    - "duplicate"

- name: "enhancement 🔝"
  color: "D5BBED"
  description: "Issue or PR releated to a enhancement to an existing feature"
  aliases:
    - "enhancement"

- name: "evolvability ♻️"
  color: "008672"
  description: "Issue or PR launched to ensure the project's evolvability. Aka refactoring, clean code, etc."
  aliases:
    - "evolvability"

- name: "epic"
  color: "1D0080"
  description: "A large initiative grouping multiple user stories or features"
  aliases:
    - "epic"

- name: "feature request ➕"
  color: "5319E7"
  description: "Issue about a new feature request"
  aliases:
    - "feature request"

- name: "feature ➕"
  color: "7828E5"
  description: "New features added. Use only after approve feature request"
  aliases:
    - "feature"

- name: "frontend"
  color: "E1A000"
  description: "Issue or PR related to frontend (UI/UX) implementation"
  aliases:
    - "frontend"

- name: "good first issue 🧠"
  color: "CA3AC2"
  description: "Issue good for newcomers"
  aliases:
    - "good first issue"

- name: "question ✋"
  color: "D876E3"
  description: "Further information is requested"
  aliases:
    - "question"

- name: "rejected ❌"
  color: "B52816"
  description: "Issue or pull request rejected"
  aliases:
    - "rejected"

- name: "release ↗️"
  color: "81A5DC"
  description: "To be set only on release PR"
  aliases:
    - "release"

- name: "security 🛡️"
  color: "D93F0B"
  description: "This PR resolves some security issue"
  aliases:
    - "security"

- name: "size/L"
  color: "CB9E0A"
  description: "This PR changes 100-499 lines, ignoring generated files. Setted automatically"

- name: "size/M"
  color: "E1B207"
  description: "This PR changes 30-99 lines, ignoring generated files. Setted automatically"

- name: "size/S"
  color: "F3C511"
  description: "This PR changes 10-29 lines, ignoring generated files. Setted automatically"

- name: "size/XL"
  color: "B68A0D"
  description: "This PR changes 500-999 lines, ignoring generated files. Setted automatically"

- name: "size/XS"
  color: "FFDB4D"
  description: "This PR changes 0-9 lines, ignoring generated files. Setted automatically"

- name: "size/XXL"
  color: "9B770A"
  description: "This PR changes over 1,000 lines, ignoring the generated files. Setted automatically"

- name: "triage 🔍"
  color: "B60205"
  description: "This issue needs to be triaged"
  aliases:
    - "triage"

- name: "user story 🎯"
  color: "6A42EB"
  description: "A new user story"
  aliases:
    - "user story"

- name: "vulnerability 🚨"
  color: "B60205"
  description: "Vulnerability detected"
  aliases:
    - "vulnerability"

- name: "wontfix 🤷‍♀️"
  color: "FFFFFF"
  description: "This issue will not be worked on"
  aliases:
    - "wontfix"